import { auth } from "@/auth"
import ProviderTree from "@/context/provider-tree"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  let session = await auth()
  console.log("session", session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderTree session={session}>{children}</ProviderTree>
      </body>
    </html>
  )
}
